[tool.ruff]
extend-exclude = [
    ".venv",
    "init_db.py"
]
line-length = 100

[tool.ruff.lint]
# https://docs.astral.sh/ruff/settings
ignore = [
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "W191",  # indentation contains tabs
    "E501",  # line too long, handled by formatter
    "N818",  # error-suffix-on-exception-name, controversial
    "RUF012", # mutable-class-default, controversial
]
# https://docs.astral.sh/ruff/rules/
select = [
    # ----------- Musthave ----------
    "E",   # pycodestyle errors     |
    "W",   # pycodestyle warnings   |
    "F",   # pyflakes               |
    "I",   # isort                  |
    "C",   # flake8-comprehensions  |
    "B",   # flake8-bugbear         |
    "N",   # pep8 namings           |
    "UP",  # pyupgrade              |
    "RUF", # ruff-specific rules    |
    # -------------------------------
    "T10",  # debugger usage
]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint.per-file-ignores]
"src/models/__init__.py" = ["F403"]  # starred import ignore

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[tool.ruff.lint.isort]
lines-after-imports = 2
split-on-trailing-comma = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "error",
    "ignore::DeprecationWarning:",
]
