from src.models.audit_log import *
from src.models.computer import *
from src.models.computer_assignment import *
from src.models.department import *
from src.models.installation import *
from src.models.license import *
from src.models.software import *
from src.models.software_type import *
from src.models.user import *
from src.models.vendor import *
